// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/teleworker/v1/teleworker.proto

package teleworkerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNSPECIFIED JobStatus = 0
	JobStatus_JOB_STATUS_SUBMITTED   JobStatus = 1
	JobStatus_JOB_STATUS_RUNNING     JobStatus = 2
	JobStatus_JOB_STATUS_SUCCESS     JobStatus = 3
	JobStatus_JOB_STATUS_FAILED      JobStatus = 4
	JobStatus_JOB_STATUS_KILLED      JobStatus = 5
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_SUBMITTED",
		2: "JOB_STATUS_RUNNING",
		3: "JOB_STATUS_SUCCESS",
		4: "JOB_STATUS_FAILED",
		5: "JOB_STATUS_KILLED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED": 0,
		"JOB_STATUS_SUBMITTED":   1,
		"JOB_STATUS_RUNNING":     2,
		"JOB_STATUS_SUCCESS":     3,
		"JOB_STATUS_FAILED":      4,
		"JOB_STATUS_KILLED":      5,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_teleworker_v1_teleworker_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_proto_teleworker_v1_teleworker_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_teleworker_v1_teleworker_proto_rawDescGZIP(), []int{0}
}

type StartJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"` // Command to run.
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`       // Arguments to give to the command.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartJobRequest) Reset() {
	*x = StartJobRequest{}
	mi := &file_proto_teleworker_v1_teleworker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartJobRequest) ProtoMessage() {}

func (x *StartJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teleworker_v1_teleworker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartJobRequest.ProtoReflect.Descriptor instead.
func (*StartJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_teleworker_v1_teleworker_proto_rawDescGZIP(), []int{0}
}

func (x *StartJobRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *StartJobRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type StartJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"` // Only contains ID for the job that was submitted.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartJobResponse) Reset() {
	*x = StartJobResponse{}
	mi := &file_proto_teleworker_v1_teleworker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartJobResponse) ProtoMessage() {}

func (x *StartJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teleworker_v1_teleworker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartJobResponse.ProtoReflect.Descriptor instead.
func (*StartJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_teleworker_v1_teleworker_proto_rawDescGZIP(), []int{1}
}

func (x *StartJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// Query the status of the job, used by `telerun status ...`
type GetJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusRequest) Reset() {
	*x = GetJobStatusRequest{}
	mi := &file_proto_teleworker_v1_teleworker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusRequest) ProtoMessage() {}

func (x *GetJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teleworker_v1_teleworker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_teleworker_v1_teleworker_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        JobStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=teleworker.v1.JobStatus" json:"status,omitempty"`
	ExitCode      *int32                 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3,oneof" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusResponse) Reset() {
	*x = GetJobStatusResponse{}
	mi := &file_proto_teleworker_v1_teleworker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusResponse) ProtoMessage() {}

func (x *GetJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teleworker_v1_teleworker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusResponse.ProtoReflect.Descriptor instead.
func (*GetJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_teleworker_v1_teleworker_proto_rawDescGZIP(), []int{3}
}

func (x *GetJobStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetJobStatusResponse) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *GetJobStatusResponse) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

// Request the output of stdout and stderr, used by `telerun logs ...`
type StreamOutputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOutputRequest) Reset() {
	*x = StreamOutputRequest{}
	mi := &file_proto_teleworker_v1_teleworker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOutputRequest) ProtoMessage() {}

func (x *StreamOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teleworker_v1_teleworker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOutputRequest.ProtoReflect.Descriptor instead.
func (*StreamOutputRequest) Descriptor() ([]byte, []int) {
	return file_proto_teleworker_v1_teleworker_proto_rawDescGZIP(), []int{4}
}

func (x *StreamOutputRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// Receive the output of stdout and stderr, used by `telerun logs ...`
type StreamOutputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOutputResponse) Reset() {
	*x = StreamOutputResponse{}
	mi := &file_proto_teleworker_v1_teleworker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOutputResponse) ProtoMessage() {}

func (x *StreamOutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teleworker_v1_teleworker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOutputResponse.ProtoReflect.Descriptor instead.
func (*StreamOutputResponse) Descriptor() ([]byte, []int) {
	return file_proto_teleworker_v1_teleworker_proto_rawDescGZIP(), []int{5}
}

func (x *StreamOutputResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type StopJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopJobRequest) Reset() {
	*x = StopJobRequest{}
	mi := &file_proto_teleworker_v1_teleworker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopJobRequest) ProtoMessage() {}

func (x *StopJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teleworker_v1_teleworker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopJobRequest.ProtoReflect.Descriptor instead.
func (*StopJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_teleworker_v1_teleworker_proto_rawDescGZIP(), []int{6}
}

func (x *StopJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type StopJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopJobResponse) Reset() {
	*x = StopJobResponse{}
	mi := &file_proto_teleworker_v1_teleworker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopJobResponse) ProtoMessage() {}

func (x *StopJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teleworker_v1_teleworker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopJobResponse.ProtoReflect.Descriptor instead.
func (*StopJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_teleworker_v1_teleworker_proto_rawDescGZIP(), []int{7}
}

var File_proto_teleworker_v1_teleworker_proto protoreflect.FileDescriptor

const file_proto_teleworker_v1_teleworker_proto_rawDesc = "" +
	"\n" +
	"$proto/teleworker/v1/teleworker.proto\x12\rteleworker.v1\"?\n" +
	"\x0fStartJobRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\")\n" +
	"\x10StartJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\",\n" +
	"\x13GetJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x8f\x01\n" +
	"\x14GetJobStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.teleworker.v1.JobStatusR\x06status\x12 \n" +
	"\texit_code\x18\x03 \x01(\x05H\x00R\bexitCode\x88\x01\x01B\f\n" +
	"\n" +
	"_exit_code\",\n" +
	"\x13StreamOutputRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"*\n" +
	"\x14StreamOutputResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"'\n" +
	"\x0eStopJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x11\n" +
	"\x0fStopJobResponse*\x9f\x01\n" +
	"\tJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14JOB_STATUS_SUBMITTED\x10\x01\x12\x16\n" +
	"\x12JOB_STATUS_RUNNING\x10\x02\x12\x16\n" +
	"\x12JOB_STATUS_SUCCESS\x10\x03\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x04\x12\x15\n" +
	"\x11JOB_STATUS_KILLED\x10\x052\xd7\x02\n" +
	"\n" +
	"TeleWorker\x12K\n" +
	"\bStartJob\x12\x1e.teleworker.v1.StartJobRequest\x1a\x1f.teleworker.v1.StartJobResponse\x12W\n" +
	"\fGetJobStatus\x12\".teleworker.v1.GetJobStatusRequest\x1a#.teleworker.v1.GetJobStatusResponse\x12Y\n" +
	"\fStreamOutput\x12\".teleworker.v1.StreamOutputRequest\x1a#.teleworker.v1.StreamOutputResponse0\x01\x12H\n" +
	"\aStopJob\x12\x1d.teleworker.v1.StopJobRequest\x1a\x1e.teleworker.v1.StopJobResponseBDZBgithub.com/kkloberdanz/teleworker/proto/teleworker/v1;teleworkerv1b\x06proto3"

var (
	file_proto_teleworker_v1_teleworker_proto_rawDescOnce sync.Once
	file_proto_teleworker_v1_teleworker_proto_rawDescData []byte
)

func file_proto_teleworker_v1_teleworker_proto_rawDescGZIP() []byte {
	file_proto_teleworker_v1_teleworker_proto_rawDescOnce.Do(func() {
		file_proto_teleworker_v1_teleworker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_teleworker_v1_teleworker_proto_rawDesc), len(file_proto_teleworker_v1_teleworker_proto_rawDesc)))
	})
	return file_proto_teleworker_v1_teleworker_proto_rawDescData
}

var file_proto_teleworker_v1_teleworker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_teleworker_v1_teleworker_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_teleworker_v1_teleworker_proto_goTypes = []any{
	(JobStatus)(0),               // 0: teleworker.v1.JobStatus
	(*StartJobRequest)(nil),      // 1: teleworker.v1.StartJobRequest
	(*StartJobResponse)(nil),     // 2: teleworker.v1.StartJobResponse
	(*GetJobStatusRequest)(nil),  // 3: teleworker.v1.GetJobStatusRequest
	(*GetJobStatusResponse)(nil), // 4: teleworker.v1.GetJobStatusResponse
	(*StreamOutputRequest)(nil),  // 5: teleworker.v1.StreamOutputRequest
	(*StreamOutputResponse)(nil), // 6: teleworker.v1.StreamOutputResponse
	(*StopJobRequest)(nil),       // 7: teleworker.v1.StopJobRequest
	(*StopJobResponse)(nil),      // 8: teleworker.v1.StopJobResponse
}
var file_proto_teleworker_v1_teleworker_proto_depIdxs = []int32{
	0, // 0: teleworker.v1.GetJobStatusResponse.status:type_name -> teleworker.v1.JobStatus
	1, // 1: teleworker.v1.TeleWorker.StartJob:input_type -> teleworker.v1.StartJobRequest
	3, // 2: teleworker.v1.TeleWorker.GetJobStatus:input_type -> teleworker.v1.GetJobStatusRequest
	5, // 3: teleworker.v1.TeleWorker.StreamOutput:input_type -> teleworker.v1.StreamOutputRequest
	7, // 4: teleworker.v1.TeleWorker.StopJob:input_type -> teleworker.v1.StopJobRequest
	2, // 5: teleworker.v1.TeleWorker.StartJob:output_type -> teleworker.v1.StartJobResponse
	4, // 6: teleworker.v1.TeleWorker.GetJobStatus:output_type -> teleworker.v1.GetJobStatusResponse
	6, // 7: teleworker.v1.TeleWorker.StreamOutput:output_type -> teleworker.v1.StreamOutputResponse
	8, // 8: teleworker.v1.TeleWorker.StopJob:output_type -> teleworker.v1.StopJobResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_teleworker_v1_teleworker_proto_init() }
func file_proto_teleworker_v1_teleworker_proto_init() {
	if File_proto_teleworker_v1_teleworker_proto != nil {
		return
	}
	file_proto_teleworker_v1_teleworker_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_teleworker_v1_teleworker_proto_rawDesc), len(file_proto_teleworker_v1_teleworker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_teleworker_v1_teleworker_proto_goTypes,
		DependencyIndexes: file_proto_teleworker_v1_teleworker_proto_depIdxs,
		EnumInfos:         file_proto_teleworker_v1_teleworker_proto_enumTypes,
		MessageInfos:      file_proto_teleworker_v1_teleworker_proto_msgTypes,
	}.Build()
	File_proto_teleworker_v1_teleworker_proto = out.File
	file_proto_teleworker_v1_teleworker_proto_goTypes = nil
	file_proto_teleworker_v1_teleworker_proto_depIdxs = nil
}
