// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/teleworker/v1/teleworker.proto

package teleworkerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TeleWorker_StartJob_FullMethodName     = "/teleworker.v1.TeleWorker/StartJob"
	TeleWorker_GetJobStatus_FullMethodName = "/teleworker.v1.TeleWorker/GetJobStatus"
	TeleWorker_StreamOutput_FullMethodName = "/teleworker.v1.TeleWorker/StreamOutput"
	TeleWorker_StopJob_FullMethodName      = "/teleworker.v1.TeleWorker/StopJob"
)

// TeleWorkerClient is the client API for TeleWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TeleWorkerClient interface {
	StartJob(ctx context.Context, in *StartJobRequest, opts ...grpc.CallOption) (*StartJobResponse, error)
	GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error)
	StreamOutput(ctx context.Context, in *StreamOutputRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamOutputResponse], error)
	StopJob(ctx context.Context, in *StopJobRequest, opts ...grpc.CallOption) (*StopJobResponse, error)
}

type teleWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewTeleWorkerClient(cc grpc.ClientConnInterface) TeleWorkerClient {
	return &teleWorkerClient{cc}
}

func (c *teleWorkerClient) StartJob(ctx context.Context, in *StartJobRequest, opts ...grpc.CallOption) (*StartJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartJobResponse)
	err := c.cc.Invoke(ctx, TeleWorker_StartJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teleWorkerClient) GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobStatusResponse)
	err := c.cc.Invoke(ctx, TeleWorker_GetJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teleWorkerClient) StreamOutput(ctx context.Context, in *StreamOutputRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamOutputResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TeleWorker_ServiceDesc.Streams[0], TeleWorker_StreamOutput_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamOutputRequest, StreamOutputResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TeleWorker_StreamOutputClient = grpc.ServerStreamingClient[StreamOutputResponse]

func (c *teleWorkerClient) StopJob(ctx context.Context, in *StopJobRequest, opts ...grpc.CallOption) (*StopJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopJobResponse)
	err := c.cc.Invoke(ctx, TeleWorker_StopJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TeleWorkerServer is the server API for TeleWorker service.
// All implementations must embed UnimplementedTeleWorkerServer
// for forward compatibility.
type TeleWorkerServer interface {
	StartJob(context.Context, *StartJobRequest) (*StartJobResponse, error)
	GetJobStatus(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error)
	StreamOutput(*StreamOutputRequest, grpc.ServerStreamingServer[StreamOutputResponse]) error
	StopJob(context.Context, *StopJobRequest) (*StopJobResponse, error)
	mustEmbedUnimplementedTeleWorkerServer()
}

// UnimplementedTeleWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTeleWorkerServer struct{}

func (UnimplementedTeleWorkerServer) StartJob(context.Context, *StartJobRequest) (*StartJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartJob not implemented")
}
func (UnimplementedTeleWorkerServer) GetJobStatus(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJobStatus not implemented")
}
func (UnimplementedTeleWorkerServer) StreamOutput(*StreamOutputRequest, grpc.ServerStreamingServer[StreamOutputResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamOutput not implemented")
}
func (UnimplementedTeleWorkerServer) StopJob(context.Context, *StopJobRequest) (*StopJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopJob not implemented")
}
func (UnimplementedTeleWorkerServer) mustEmbedUnimplementedTeleWorkerServer() {}
func (UnimplementedTeleWorkerServer) testEmbeddedByValue()                    {}

// UnsafeTeleWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TeleWorkerServer will
// result in compilation errors.
type UnsafeTeleWorkerServer interface {
	mustEmbedUnimplementedTeleWorkerServer()
}

func RegisterTeleWorkerServer(s grpc.ServiceRegistrar, srv TeleWorkerServer) {
	// If the following call panics, it indicates UnimplementedTeleWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TeleWorker_ServiceDesc, srv)
}

func _TeleWorker_StartJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeleWorkerServer).StartJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeleWorker_StartJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeleWorkerServer).StartJob(ctx, req.(*StartJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeleWorker_GetJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeleWorkerServer).GetJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeleWorker_GetJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeleWorkerServer).GetJobStatus(ctx, req.(*GetJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeleWorker_StreamOutput_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamOutputRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TeleWorkerServer).StreamOutput(m, &grpc.GenericServerStream[StreamOutputRequest, StreamOutputResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TeleWorker_StreamOutputServer = grpc.ServerStreamingServer[StreamOutputResponse]

func _TeleWorker_StopJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeleWorkerServer).StopJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeleWorker_StopJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeleWorkerServer).StopJob(ctx, req.(*StopJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TeleWorker_ServiceDesc is the grpc.ServiceDesc for TeleWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TeleWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "teleworker.v1.TeleWorker",
	HandlerType: (*TeleWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartJob",
			Handler:    _TeleWorker_StartJob_Handler,
		},
		{
			MethodName: "GetJobStatus",
			Handler:    _TeleWorker_GetJobStatus_Handler,
		},
		{
			MethodName: "StopJob",
			Handler:    _TeleWorker_StopJob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamOutput",
			Handler:       _TeleWorker_StreamOutput_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/teleworker/v1/teleworker.proto",
}
